### PR TITLE
Add Scarfolk logo, code cleanup

### PR DESCRIPTION
**Pull request by deberny**
Trello [6-look-and-feel-like-a-council-site](https://trello.com/c/EN5neKis/)
screen shot 2018-07-09 at 14 03 06

I couldn't find any copyrights restrictions on Scarfolk logo, so created the same one. 
We might want to change it for external demos?

### CODE REVIEW

**Comment by deberny** [comment]
[Look and feel like a council site](https://trello.com/c/EN5neKis/6-look-and-feel-like-a-council-site)

**Review by robbiepaul — APPROVED** [review]
The logo doesn’t seem vertically aligned with the text, but other than that it looks great. Happy to merge if you are

**Comment by deberny** [comment]
yes, it's aligned to the bottom, but it looks a bit off because it's circle. Let me try middle-alignment.

**Comment by deberny** [comment]
@robbiepaul pushed an update

screen shot 2018-07-09 at 15 42 41

**Comment by robbiepaul** [comment]
@deberny awesome

**Pull request merged**
